%% 1. Initialize Experiment Configuration
% The options define the type of data to compare with in the inversion
% Options: 'LABref', 'Standard-linear' or 'Standard-sinusoidal'
experimentType = 'Standard-linear'; 
cfg = get_inversion_config(experimentType);

cfg.forward_method = 1; % method 1 (split-domain) or method 2 (entire-domain)

% MCMC Parameters
cfg.nstep = 5e5; % number of MCMC steps
cfg.h = ceil(max(cfg.maxDepth/cfg.nel_y, cfg.Long_X/cfg.nel_x));    % characteristic mesh size
cfg.sigma_d = 0.25 * cfg.h;  % data uncertainty
cfg.len_prop = 1.0 * cfg.h; % propagation length of the proposal distribution

cfg.plot_cut_elements = 0;   % 0 or 1 to plot the elements and interface while doing the inversion
% Type of data to invert
cfg.inversion_case = 'flux_sup'; % cases: 'Temp_Omega'; 'Temp_sup', 'flux_sup'

% Set a unique name for saving (also) intermediate results
save_name = generateNames2save(cfg);

%% 2. Run Inversion
[inverted_var, error_vec, phi_t, accepted, rejected, time_inv, rel_dof, Mesh, Prob] = ...
    inver_funct_checkp(...
        cfg.forward_method, ...
        cfg.inversion_case, ...
        cfg.dirichlet_condition, ...
        cfg.Long_X, ...
        cfg.maxDepth, ...
        cfg.nel_x, ...
        cfg.nel_y, ...
        cfg.sigma_d, ...
        cfg.len_prop, ...
        cfg.LAB_definition, ...
        cfg.nstep, ...
        cfg.Data_obs, ...
        cfg.plot_cut_elements, ...
        cfg.consider_convection, ...
        cfg.LAB_priorGeometry, ...
        cfg.make_up, ...
        save_name ...
    );

%% 3. Save Results
save(save_name, 'inverted_var', 'error_vec', 'phi_t', 'accepted', 'rejected', 'time_inv','rel_dof', '-v7.3');